management:
  endpoints:
    web:
      exposure:
        include: [ "health", "info", "metrics", "bindings", "beans", "env", "loggers", "mappings" ]

server:
  port: 8080

spring:
  config:
    name: Cake manager server
  datasource:
    url: jdbc:h2:mem:waracle;MODE=MySQL
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: com.waracle.cakemanagerserver.jpa.hibernate.PhysicalNamingStrategyImpl
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:db/schema.sql,classpath:db/data.sql
